### ISSUE TITLE
Is there any Bongo demo?

### ISSUE THREAD

**Issue by topstarnetwork** [bongo-project/bongo#1]
Is there any Bongo demo?

**Comment by lhaig** [comment]
Hi Heather, 
Unfortunately not.
We have not had much development on the code in a while due to people having lives.
The code will need updating to the current levels before you could use it.

Lance

**Comment by lhaig** [comment]
Do you know any C developers :-)

**Comment by topstarnetwork** [comment]
Thanks though!
